### ISSUE TITLE
Big issue

### ISSUE THREAD

**Issue by Mikkk768** [SupernovaBotDeveloper/dbd.jsMultipurposeBot#2]
### All commands are stolen, u didn't even make it, all credits go to **Leaf#9392**

**Comment by SupernovaBotDeveloper** [comment]
Ok I'm crediting him, don't be mad!

**Comment by SupernovaBotDeveloper** [comment]
Hey Motherfucker,not all Commands are stolen some commands are made by me and Baeriri,so shut the fuck up

**Comment by Mikkk768** [comment]
bastardo coglione bocchinaro figlio di troia vai da tua madre e sputala in faccia coglione,

**Comment by SupernovaBotDeveloper** [comment]
Bruh
